name: Bug report
description: Report a reproducible problem with claude-relais
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Exact commands and environment
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant output
      description: Include preflight/smoke/contract output if available
